name: Tests

on:
  push:
    branches:
      - "**"

jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - uses: ./.github/actions/setup-poetry
        with:
          poetry-version: 1.1.8

      - name: Cache poetry modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-poetry-modules-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Run static code analysis
        run: poetry run poe lint

  unit-tests:
    runs-on: ubuntu-latest
    needs: [static-tests]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - uses: ./.github/actions/setup-poetry
        with:
          poetry-version: 1.1.8

      - name: Cache poetry modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-poetry-modules-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run poe test
